import BitBlocksVideo from "components/BitBlocksVideo";
import Head from "next/head";

export default function Home() {
  const images = [
    "https://ord-mirror.magiceden.dev/content/995c480460912253bb319c7a988889160dc2effc46115dcc33ff13b8521d6a69i0",
    "https://ord-mirror.magiceden.dev/content/715f4243b7a6d044a692aa4440b6da5ee8f45567c1265af076166cb331b085e8i0",
  ];
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b  to-[#15162c]">
        <BitBlocksVideo bitblock={images[0] ?? ""} />
      </main>
    </>
  );
}
