import DoubleImage from "components/DoubleImage";
import Head from "next/head";

export default function Home() {
  const originalImage = [
    "https://renderer.magiceden.dev/v2/render?id=6686417ec7f2f8033da9757946c496c136d75ade2bd0ac183cff331acb7e0f11i0",
    "https://renderer.magiceden.dev/v2/render?id=6686417ec7f2f8033da9757946c496c136d75ade2bd0ac183cff331acb7e0f11i0",
  ];
  const hoverImage = [
    "https://ord-mirror.magiceden.dev/content/1908cfd74c89039931aa01da746ca48704642cb0ebd7d1acc66cdf3782802b63i0",
    "https://ord-mirror.magiceden.dev/content/1908cfd74c89039931aa01da746ca48704642cb0ebd7d1acc66cdf3782802b63i0",
  ];
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b  to-[#15162c]">
        <DoubleImage
          mainImg={originalImage[0] ?? ""}
          hoverImg={hoverImage[0] ?? ""}
        />
      </main>
    </>
  );
}
